// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Onyx.Products.Infrastructure.DbContexts;

#nullable disable

namespace Onyx.Products.Infrastructure.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Onyx.Products.Infrastructure.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Colour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25320c5e-f58a-4b1f-b63a-8ee07a840bdf"),
                            Category = 0,
                            Colour = 8,
                            Description = "High-end smartphone with advanced features",
                            Name = "Smartphone",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = new Guid("1efe7a31-8dcc-4ff0-9b2d-5f148e2989cc"),
                            Category = 1,
                            Colour = 2,
                            Description = "Cotton T-shirt for casual wear",
                            Name = "T-shirt",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = new Guid("aefe7a31-8dcc-4ff0-9b2d-5f148e2989c6"),
                            Category = 9,
                            Colour = 1,
                            Description = "Programmable coffee maker for home use",
                            Name = "Coffee Maker",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = new Guid("befe7a31-8dcc-4ff0-9b2d-5f148e2989c7"),
                            Category = 3,
                            Colour = 0,
                            Description = "Matte lipstick in bold red shade",
                            Name = "Lipstick",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = new Guid("cefe7a31-8dcc-4ff0-9b2d-5f148e2989c8"),
                            Category = 4,
                            Colour = 9,
                            Description = "First book in the Harry Potter series",
                            Name = "Harry Potter and the Philosopher's Stone",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = new Guid("defe7a31-8dcc-4ff0-9b2d-5f148e2989c9"),
                            Category = 5,
                            Colour = 10,
                            Description = "Buildable LEGO model of the Millennium Falcon",
                            Name = "LEGO Star Wars Millennium Falcon",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = new Guid("eefe7a31-8dcc-4ff0-9b2d-5f148e2989ca"),
                            Category = 6,
                            Colour = 8,
                            Description = "Official size and weight football",
                            Name = "Football",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = new Guid("fefe7a31-8dcc-4ff0-9b2d-5f148e2989cb"),
                            Category = 10,
                            Colour = 2,
                            Description = "Portable vacuum cleaner for cars",
                            Name = "Car Vacuum Cleaner",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = new Guid("1ffe7a31-8dcc-4ff0-9b2d-5f148e2989cc"),
                            Category = 11,
                            Colour = 1,
                            Description = "Daily multivitamin tablets for adults",
                            Name = "Multivitamin Tablets",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = new Guid("2ffe7a31-8dcc-4ff0-9b2d-5f148e2989cd"),
                            Category = 8,
                            Colour = 2,
                            Description = "3-seater sofa with fabric upholstery",
                            Name = "Sofa",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = new Guid("3ffe7a31-8dcc-4ff0-9b2d-5f148e2989ce"),
                            Category = 12,
                            Colour = 0,
                            Description = "Fresh, juicy apples",
                            Name = "Apples",
                            Price = 2.49m
                        },
                        new
                        {
                            Id = new Guid("56e40388-6f31-4548-904b-cc4ba8d0bc8e"),
                            Category = 13,
                            Colour = 8,
                            Description = "A5 size ruled notebook",
                            Name = "Notebook",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = new Guid("4ffe7a31-8dcc-4ff0-9b2d-5f148e2989cf"),
                            Category = 4,
                            Colour = 2,
                            Description = "Adjustable dog collar for medium-sized dogs",
                            Name = "Dog Collar",
                            Price = 14.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
